Fix crash because of a zero value cert in cache
caddyserver/certmagic pull request #177
Opened 2022-03-22 10:26 UTC by skeetmtp

Hello,

I got again the very uncommon crash I talked about on the forum: https://caddy.community/t/strange-invalid-memory-address-or-nil-pointer-dereference-with-custom-build/13867

And I'm happy to say I found the issue ! :) 
So, here is my PR to fix it, but feel free to do it in another way if you wish, as I have almost zero XP in golang.

The root cause, is updateOCSPStaples() inserting a zeroed cert into cache.

The full chain of events:
* a cert A is pushed to the `updated` queue in `updateOCSPStaples()`
* in parallel a new cert B is evicting this very same cert A from the full cache, to make some room.
* `updateOCSPStaples()` while iterating `updated` queue is trying to get cert A from cache, but got a zeroed struct, update some fields, and insert this zeroed cert to cache.
* finally a new cert C is trying to evict a random cert, if unlucky, the random cert is cert A, and so there is a call to  `removeCertificate()` on a zeroed cert, resulting in a "invalid memory address or nil pointer dereference" error

Here some extract of logs:
See cert trail.withconelabs.com being evict, **then** being updated
Also, later on we can see empty `removing_subjects` in log when trying to evict the zeroed cert

```
2022-03-19 20:00:12	{"level":"debug","ts":1647716412.2069285,"logger":"tls.cache","msg":"cache full; evicting random certificate","removing_subjects":["trail.withconelabs.com"],"removing_hash":"44ab6dbc3cee44f456d8065a9709cf894a3463ccfc2d760d3293e524f2a551a1","inserting_subjects":["trail.trymyui.app"],"inserting_hash":"03cd95e0317a1085d9869b52ad3427cba6c1fde3223c4823d862a0eb52e92678"}
2022-03-19 20:00:12	{"level":"debug","ts":1647716412.20698,"logger":"tls.cache","msg":"removed certificate from cache","subjects":["trail.withconelabs.com"],"expiration":1652399999,"managed":true,"issuer_key":"acme.zerossl.com-v2-DV90","hash":"44ab6dbc3cee44f456d8065a9709cf894a3463ccfc2d760d3293e524f2a551a1","cache_size":9999,"cache_capacity":10000}
2022-03-19 20:00:14	{"level":"info","ts":1647716414.186718,"logger":"tls.cache.maintenance","msg":"advancing OCSP staple","identifiers":["trail.withconelabs.com"],"from":1648018697,"to":1648321096}
...
2022-03-19 20:47:11 {"level":"debug","ts":1647719230.8803022,"logger":"tls.cache","msg":"cache full; evicting random certificate","removing_subjects":[],"removing_hash":"","inserting_subjects":["trail.crossingminds.com"],"inserting_hash":"e6bcb46c703993204c37d7c955bbe3a2086197f6ca8e340b08b545cf261f8f9e"}
2022-03-19 20:47:11 {"level":"debug","ts":1647719230.8815231,"logger":"http.stdlib","msg":"http: panic serving 54.174.54.48:48904: runtime error: invalid memory address or nil pointer dereference\ngoroutine 13084358 [running]:\nnet/http.(*conn).serve.func1(0xc0124617c0)\n\t/usr/local/go/src/net/http/server.go:1824 +0x153\npanic(0x16d7ac0, 0x25baad0)\n\t/usr/local/go/src/runtime/panic.go:971 +0x499\ngithub.com/caddyserver/certmagic.(*Cache).removeCertificate(0xc0002b87e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0087abe00, ...)\
```

2022-03-22 20:51 UTC, mholt commented
Thanks, am looking into this. Can you post the full log though? This one is truncated.

2022-03-22 21:31 UTC, mholt requested changes
As far as the change goes, it LGTM. Just a nit about style to make it more conventional. But good job with the change!

I think this is good logic... we don't want to be adding a partial cert to the cache unintentionally. Am still interested in the full log for the record, but yeah, thanks for tracking it down!

2022-03-22 21:31 UTC, mholt commented on maintain.go
> +		if found {
```suggestion
		if cert, ok := certCache.cache[certKey]; ok {
```

Just a little more conventional Go style here :)

2022-03-22 21:40 UTC, francislavoie commented
@mholt I think https://caddy.community/t/strange-invalid-memory-address-or-nil-pointer-dereference-with-custom-build/13867/2 has the panic log you're asking for

2022-03-22 21:44 UTC, mholt approved these changes
Thank you for figuring this out :pray:

2022-03-22 21:54 UTC, merged

2022-03-22 22:19 UTC, skeetmtp commented
Thanks for the swift merge!

Crash occurred only twice in 4 months, and I just made the fix a few hours ago, but indeed, for now still no crash.

For the records here the full log line
```
{"level":"debug","ts":1647719230.8815231,"logger":"http.stdlib","msg":"http: panic serving 54.174.54.48:48904: runtime error: invalid memory address or nil pointer dereference\ngoroutine 13084358 [running]:\nnet/http.(*conn).serve.func1(0xc0124617c0)\n\t/usr/local/go/src/net/http/server.go:1824 +0x153\npanic(0x16d7ac0, 0x25baad0)\n\t/usr/local/go/src/runtime/panic.go:971 +0x499\ngithub.com/caddyserver/certmagic.(*Cache).removeCertificate(0xc0002b87e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0087abe00, ...)\n\t/home/vagrant/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.6-0.20210922202800-88b8609b4d8f/cache.go:281 +0x419\ngithub.com/caddyserver/certmagic.(*Cache).unsyncedCacheCertificate(0xc0002b87e0, 0xc0208f85a0, 0x3, 0x4, 0x17d61c0, 0xc005efe450, 0x0, 0x0, 0x0, 0xc01af08c00, ...)\n\t/home/vagrant/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.6-0.20210922202800-88b8609b4d8f/cache.go:227 +0xbfd\ngithub.com/caddyserver/certmagic.(*Cache).cacheCertificate(0xc0002b87e0, 0xc0208f85a0, 0x3, 0x4, 0x17d61c0, 0xc005efe450, 0x0, 0x0, 0x0, 0xc01af08c00, ...)\n\t/home/vagrant/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.6-0.20210922202800-88b8609b4d8f/cache.go:184 +0x98\ngithub.com/caddyserver/certmagic.(*Config).CacheManagedCertificate(0xc014106140, 0xc01c6431e8, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/vagrant/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.6-0.20210922202800-88b8609b4d8f/certificates.go:114 +0x1a5\ngithub.com/caddyserver/certmagic.(*Config).getCertDuringHandshake(0xc014106140, 0xc0096dd080, 0xe50a16574d20101, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/vagrant/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.6-0.20210922202800-88b8609b4d8f/handshake.go:271 +0x17a6\ngithub.com/caddyserver/certmagic.(*Config).GetCertificate(0xc014106140, 0xc0096dd080, 0x17, 0xc00047dce0, 0x7f1f522fca68)\n\t/home/vagrant/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.6-0.20210922202800-88b8609b4d8f/handshake.go:66 +0x118\ngithub.com/caddyserver/caddy/v2/modules/caddytls.(*ConnectionPolicy).buildStandardTLSConfig.func1(0xc0096dd080, 0x410018, 0xb8, 0x1834fe0)\n\t/home/vagrant/caddy/modules/caddytls/connpolicy.go:185 +0x10f\ncrypto/tls.(*Config).getCertificate(0xc0004e3b00, 0xc0096dd080, 0xc0096dd080, 0xc000cca078, 0x25503ec)\n\t/usr/local/go/src/crypto/tls/common.go:1017 +0x3cb\ncrypto/tls.(*serverHandshakeStateTLS13).pickCertificate(0xc015eafa20, 0x0, 0x0)\n\t/usr/local/go/src/crypto/tls/handshake_server_tls13.go:377 +0x75\ncrypto/tls.(*serverHandshakeStateTLS13).handshake(0xc015eafa20, 0xc00a461200, 0x0)\n\t/usr/local/go/src/crypto/tls/handshake_server_tls13.go:52 +0x7f\ncrypto/tls.(*Conn).serverHandshake(0xc014d38000, 0xc01fe4e7b0, 0x12)\n\t/usr/local/go/src/crypto/tls/handshake_server.go:51 +0xd4\ncrypto/tls.(*Conn).Handshake(0xc014d38000, 0x0, 0x0)\n\t/usr/local/go/src/crypto/tls/conn.go:1391 +0xc9\nnet/http.(*conn).serve(0xc0124617c0, 0x1bcc958, 0xc000527950)\n\t/usr/local/go/src/net/http/server.go:1840 +0x1a5\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:3013 +0x39b"}
--
```

2022-03-23 18:13 UTC, mholt commented
Ah ok. Well a few hours out of 4 months isn't very much time, so I guess we'll see how it goes.